import type { Route, RouteWithCost } from '../core/types'

// Re-export the type for convenience
export type { RouteWithCost }

/**
 * Gets cached routes for a specific chain ID
 * @param chainId - The chain ID to get cached routes for
 * @returns Promise resolving to the cached routes or undefined if not available
 */
export async function getCachedRoutes(
  chainId: number
): Promise<readonly (Route | RouteWithCost)[] | undefined> {
  try {
    switch (chainId) {
      case 42220:
        // @ts-ignore - Cache files are generated by scripts and may not exist yet
        return await import('../cache/routes.42220').then(
          (module) => module.routes42220
        )
      case 11142220:
        // @ts-ignore - Cache files are generated by scripts and may not exist yet
        return await import('../cache/routes.11142220').then(
          (module) => module.routes11142220
        )
      default:
        return undefined
    }
  } catch {
    return undefined
  }
}
