name: CI

env:
  CELO_MAINNET_RPC_URL: ${{secrets.CELO_MAINNET_RPC_URL}}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Restrict default permissions for security
permissions: {}

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node: ['18.x', '20.x', '22.x']

    steps:
      - name: Checkout repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 9

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:unit

      - name: Check bundle size
        run: pnpm size
